# Generated by Django 5.2.7 on 2026-02-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=400)),
                ('mobile_no', models.IntegerField(unique=True)),
                ('age', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
