# Generated by Django 5.2.7 on 2026-02-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile_no',
            field=models.BigIntegerField(unique=True),
        ),
    ]
