# Generated by Django 5.2.7 on 2026-02-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_employee_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
